"""add initial models

Revision ID: 8715184b57f6
Revises: 
Create Date: 2022-03-22 15:55:42.808928

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8715184b57f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_keys",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("valid_from", sa.DateTime(), nullable=False),
        sa.Column("valid_until", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("discriminator", sa.String(length=255), nullable=False),
        sa.Column("wallet", sa.BigInteger(), nullable=False),
        sa.Column("bank", sa.BigInteger(), nullable=False),
        sa.Column("bank_size", sa.BigInteger(), nullable=False),
        sa.Column("flags", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_daily", sa.DateTime(), nullable=True),
        sa.Column("last_weekly", sa.DateTime(), nullable=True),
        sa.Column("last_monthly", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("access_keys")
    # ### end Alembic commands ###
